name: Snyk CI Tests
## requires SNYK_TOKEN and SNYK_ORG_ID secret
on:
  workflow_dispatch:
  pull_request:
    branches: main
  push: 
    branches: main
env: 
  IMAGE_NAME: nodejs-goof-insights
  IMAGE_TAG: v1.1.0
  PLATFORM: linux/amd64
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
  SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}

jobs:
  build:
    name: Snyk Scan 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      
      - name: Build project
        run: npm install --legacy-peer-deps
  
      - name: Setup Snyk + snyk-filter # For information about the required commands https://docs.snyk.io/scm-ide-and-ci-cd-integrations/snyk-ci-cd-integrations
        run: |
          npm install snyk snyk-filter -g
          snyk auth $SNYK_TOKEN --auth-type=token
      
      - name: Snyk Open Source
        run: |
          snyk monitor --file=./package.json --tags="component=pkg:${{ github.repository }}@${{ github.ref_name }}" \
          --org=${{ secrets.SNYK_ORG_ID }} --project-name=${{ env.REPO_NAME }} \
          --remote-repo-url=${{ github.repository }} --target-reference=${{ github.repository }}

      - name: Snyk IaC
        run: snyk iac test --report --org=${{ secrets.SNYK_ORG_ID }}
        continue-on-error: true
      
      # upload container snapshot to snyk 
      - name: Snyk Container Monitor
        run: |
          snyk container monitor "${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" \
          --file=Dockerfile --exclude-app-vulns --platform=${{ env.PLATFORM }} \
          --tags="component=pkg:${{ github.repository }}@${{ github.ref_name }}" \
          --org=${{ secrets.SNYK_ORG_ID }} --target-reference=${{ github.repository }}
        continue-on-error: true

      - name: Snyk SBOM generate
        run: |
          snyk container sbom --format=spdx2.3+json \
          ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} > bom.${{ env.IMAGE_NAME }}.spdx.json
        continue-on-error: true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: snyk SBOM
          path: bom.${{ env.IMAGE_NAME }}.spdx.json
        continue-on-error: true
