name: 'Provision EKS and Deploy Demo & Connector'
on:
  workflow_dispatch:

jobs:
  provision-eks:
    name: 'Deploy Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        curl -LO https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        mkdir -p ~/.local/bin
        mv ./kubectl ~/.local/bin/kubectl
        kubectl version --client

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create EKS Cluster
      run: |
        ARCH=amd64
        PLATFORM=$(uname -s)_$ARCH
        curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
        tar -xzf ./eksctl_linux_amd64 -o ./eksctl
        chmod +x ./eksctl && mv ./eksctl ~/.local/bin/eksctl
        eksctl --version
        eksctl create cluster --name=dev-cluster --region=us-east-1 --set-kubeconfig-context

    - name: kubectl apply
      run: |
        cd k8s-setup && ./deploy.sh --connector-demo-only
