name: Snyk CD Action
# Requires DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets
on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]

env:
  IMAGE_NAME: nodejs-goof-insights
  IMAGE_TAG: v2.0.0

jobs:
  build:
    # if: ${{ github.event.pull_request.merged }}
    name: Build and push
    runs-on: ubuntu-latest
    # strategy: 
    #   matrix:
    #     platforms: ["linux/amd64", "linux/arm64"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5 
        with:
          push: true 
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Snyk SBOM generate
        run: |
          snyk container sbom --format=spdx2.3+json \
          ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} > bom.${{ github.ref }}.spdx.json
        continue-on-error: true
      
      - name: Install Notation and ORAS CLI
        run: |
          curl -fsSL https://github.com/notaryproject/notation/releases/download/v1.0.0/notation-linux-amd64.tar.gz | tar -xz -C /usr/local/bin
        # Install Notation CLI for signing artifacts (https://github.com/notaryproject/notation)

      - name: Sign SBOM with Notation
        run: |
          #TODO

      - name: Push SBOM and Signature to Registry
         # running oras as a container and attach both sbom and signature 
        run: |
          alias doras='docker run -it --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v1.2.0'  
          echo ${{ secrets.DOCKERHUB_TOKEN }} | doras attach -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          --artifact-type application/spdx+json \
          "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" \
          bom.spdx.json
        # Push SBOM and signature to registry using ORAS (https://oras.land/docs/installation)
      
      - name: Snyk Container Monitor
        run: |
          snyk container monitor "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" \
          --file=Dockerfile --exclude-app-vulns --platform=linux/amd64 \
          --tags="component=pkg:${{ github.repository }}@${{ github.ref_name }}" \
          --org=${{ secrets.SNYK_ORG_ID }} --target-reference=${{ github.repository }}

        continue-on-error: true
