name: Snyk CD Action
# Requires DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets
on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]

env:
  IMAGE_NAME: nodejs-goof-insights
  IMAGE_TAG: v2.0.0
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:
    # uncomment next line to only run if PR was merged
    # if: ${{ github.event.pull_request.merged }}
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5 
        with:
          push: true 
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Snyk SBOM generate
        run: |
          npm install snyk -g
          SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} snyk auth --auth-type=token
          snyk container sbom --format=spdx2.3+json \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} > bom.spdx.json
        continue-on-error: true
  
      - name: Install Notation and generate a default certificate
        run: |
          curl -LO https://github.com/notaryproject/notation/releases/download/v1.2.0/notation_v1.2.0\_linux_amd64.tar.gz
          mkdir -p notation-install/
          tar -zxf notation_v1.2.0_linux_amd64.tar.gz -o notation -C notation-install/ 
          sudo mv notation-install/notation /usr/local/bin/
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | notation login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          notation cert generate-test --default "wabbit-networks.io"
        # Install Notation CLI for signing artifacts (https://github.com/notaryproject/notation)

      - name: Sign SBOM with Notation
        run: |
          notation sign "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Push SBOM and Signature to Registry
         # running oras as binary sbom and signature 
        run: |
          curl -LO "https://github.com/oras-project/oras/releases/download/v1.2.0/oras_1.2.0_darwin_arm64.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_1.2.0_*.tar.gz -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | oras login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          oras attach ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          --artifact-type application/spdx+json \
          "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" \
          bom.spdx.json
        # Push SBOM and signature to registry using ORAS (https://oras.land/docs/installation)
      
      - name: Snyk Container Monitor
        run: |
          snyk container monitor "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" \
          --file=Dockerfile --exclude-app-vulns --platform=linux/amd64 \
          --tags="component=pkg:${{ github.repository }}@${{ github.ref_name }}" \
          --org=${{ secrets.SNYK_ORG_ID }} --target-reference=${{ github.repository }}

        continue-on-error: true
